### PR TITLE
Remove non-essential files from npm package

### PR DESCRIPTION
**Pull request by jorrit**
This change retains the test files

### CODE REVIEW

**Comment by feross** [comment]
Why? This saves much less than 1KB. I'm sorry, but I don't see the benefit. The way that npmignore interacts with gitignore is tricky and I'd rather not deal with it. But thanks for your PR.

**Comment by jorrit** [comment]
Do you have more information about this trickyness? Also, it's not just the bytes, but the number of inodes as well:

http://stackoverflow.com/questions/36710571/lots-of-inodes-with-node-js
npm/npm#13271

**Comment by feross** [comment]
The issue is that if there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. 

So, basically, adding an .npmignore file _unignores_ everything that's in .gitignore, which is unintuitive and surprising IMO.

I try to avoid them whenever possible.

**Comment by jorrit** [comment]
I think it is the other way around: when npm doesn't find a .npmignore file, it uses .gitignore instead. When adding a .npmignore one should copy the .gitignore file contents to it.

**Comment by feross** [comment]
Yeah, mistyped that. .npmignore overwrites .gitignore

**Pull request closed without merging**
